<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\WithMultipleSheets;

/**
 * Archive export workbook — organizes the report into logical sheets.
 */
class ArchiveExport implements WithMultipleSheets
{
    public function __construct(private array $dataset) {}

    public function sheets(): array
    {
        $sheets = [];

        // Summary sheet always present
        $sheets[] = new ArchiveSheet('Summary', [
            $this->headerRow(),
            ['Archive & Historical Report'],
            [],
            ['Filter', 'Value'],
            ...array_map(fn ($label, $value) => [$label, $value], array_keys($this->dataset['filters']), array_values($this->dataset['filters'])),
        ]);

        // Archived Records sheet
        $sheets[] = new ArchiveSheet('Archived Records', $this->recordsSheet());

        // Attendance detail sheet (only if data)
        if ($this->dataset['summary']['attendance_records'] > 0) {
            $sheets[] = new ArchiveSheet('Attendance', $this->attendanceSheet());
        }

        // Payroll detail sheet (only if data)
        if ($this->dataset['summary']['payroll_records'] > 0) {
            $sheets[] = new ArchiveSheet('Payroll', $this->payrollSheet());
        }

        // Departments sheet (only if data)
        if ($this->dataset['department_stats']->contains(fn ($d) => $d['employees'] > 0 || $d['payroll'] > 0)) {
            $sheets[] = new ArchiveSheet('Departments', $this->departmentSheet());
        }

        return $sheets;
    }

    private function headerRow(): array
    {
        return ['Generated by: '.$this->dataset['generated_by'], 'Generated: '.$this->dataset['generated_at']->format('M d, Y h:i A')];
    }

    private function recordsSheet(): array
    {
        $rows = [['Employee', 'Department', 'Record Type', 'Date', 'Period', 'Status', 'Amount', 'Archived At']];
        foreach ($this->dataset['archives'] as $a) {
            $d = is_array($a->data) ? $a->data : [];
            $amount = data_get($d, 'gross_pay') ?? data_get($d, 'net_pay') ?? data_get($d, 'additional_pay') ?? data_get($d, 'monthly_salary');
            $status = data_get($d, 'status') ?? data_get($d, 'approval_status') ?? data_get($d, 'employment_status');
            $rows[] = [
                data_get($d, 'employee.full_name') ?? data_get($d, 'employee_id') ?? 'Record #'.$a->ref_id,
                data_get($d, 'department.name') ?? data_get($d, 'employee.department.name') ?? '—',
                ucwords(str_replace('_', ' ', $a->archive_type)),
                data_get($d, 'date') ?? data_get($d, 'class_date') ?? '—',
                $a->period_label,
                $status ?? '—',
                $amount !== null ? (float) $amount : '—',
                $a->archived_at?->format('Y-m-d'),
            ];
        }

        return $rows;
    }

    private function attendanceSheet(): array
    {
        $rows = [['Month', 'Present', 'Late', 'Half Day', 'Absent']];
        foreach ($this->dataset['attendance_chart']['labels'] as $i => $label) {
            $rows[] = [
                $label,
                $this->dataset['attendance_chart']['present'][$i],
                $this->dataset['attendance_chart']['late'][$i],
                $this->dataset['attendance_chart']['half_day'][$i],
                $this->dataset['attendance_chart']['absent'][$i],
            ];
        }

        return $rows;
    }

    private function payrollSheet(): array
    {
        // Recompute actual deductions/benefits from the source-of-truth via the report service
        // for a clean Payroll sheet (gross/net only come pre-aggregated in the chart arrays).
        $rows = [['Month', 'Gross', 'Net', 'Deductions']];
        foreach ($this->dataset['payroll_chart']['labels'] as $i => $label) {
            $rows[] = [
                $label,
                $this->dataset['payroll_chart']['gross'][$i],
                $this->dataset['payroll_chart']['net'][$i],
                round($this->dataset['payroll_chart']['gross'][$i] - $this->dataset['payroll_chart']['net'][$i], 2),
            ];
        }

        return $rows;
    }

    private function departmentSheet(): array
    {
        $rows = [['Department', 'Employees', 'Attendance Rate %', 'Payroll Expense']];
        foreach ($this->dataset['department_stats'] as $d) {
            $rows[] = [$d['name'], $d['employees'], $d['attendance_rate'], $d['payroll']];
        }

        return $rows;
    }
}

