<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('biometric_agents', function (Blueprint $table) {
            $table->id();
            $table->string('agent_id', 64)->unique()->comment('stable id generated by the client agent');
            $table->string('name')->nullable();
            $table->string('computer_name', 255)->nullable();
            $table->string('api_base_url', 255)->nullable();
            $table->string('status')->default('offline'); // online | offline
            $table->timestamp('last_seen_at')->nullable();
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });

        Schema::table('attendance_logs', function (Blueprint $table) {
            $table->string('source_key', 100)->nullable()->after('punch_time');
            $table->index(['employee_id', 'source_key']);
        });
    }

    public function down(): void
    {
        Schema::table('attendance_logs', function (Blueprint $table) {
            $table->dropIndex(['employee_id', 'source_key']);
            $table->dropColumn('source_key');
        });

        Schema::dropIfExists('biometric_agents');
    }
};